# Generated by Django 5.0 on 2023-12-05 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=100, verbose_name='airline_name')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport_code', models.CharField(max_length=3, verbose_name='departure_airport_code')),
                ('arrival_airport_code', models.CharField(max_length=3, verbose_name='arrival_airport_code')),
                ('departure_date_time', models.DateTimeField(verbose_name='departure_date_time')),
                ('arrival_date_time', models.DateTimeField(verbose_name='arival_date_time')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('available_seats', models.PositiveIntegerField(verbose_name='availalbe_seats')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_airline', to='flight.airline', verbose_name='airline')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date_time', models.DateTimeField(auto_now_add=True, verbose_name='booking_date_time')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total_price')),
                ('seat_count', models.PositiveIntegerField(verbose_name='seat_count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_flight', to='flight.flight', verbose_name='flight')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_booking', to='flight.booking', verbose_name='booking')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_booking', to='flight.booking', verbose_name='booking')),
            ],
        ),
    ]
